#! /bin/bash

set -uo pipefail

# set -x

function run_remote_txn_overhead_tpcc {
        if [ $# != 17 ]; then
                print_usage
                exit -1
        fi

        typeset RESULT_DIR=$1
        typeset PROTOCOL=$2
        typeset HOST_NUM=$3
        typeset WORKER_NUM=$4
        typeset USE_CXL_TRANS=$5
        typeset USE_OUTPUT_THREAD=$6
        typeset MIGRATION_POLICY=$7
        typeset WHEN_TO_MOVE_OUT=$8
        typeset MAX_MIGRATED_ROWS_SIZE=$9
        typeset ENABLE_SCC=${10}
        typeset SCC_MECHANISM=${11}
        typeset PRE_MIGRATE=${12}
        typeset LOGGING_TYPE=${13}
        typeset WAL_GROUP_COMMIT_TIME=${14}
        typeset MODEL_CXL_SEARCH_OVERHEAD=${15}
        typeset TIME_TO_RUN=${16}
        typeset TIME_TO_WARMUP=${17}

        typeset RESULT_FILE=$RESULT_DIR/tpcc-$PROTOCOL-$HOST_NUM-$WORKER_NUM-$USE_CXL_TRANS-$USE_OUTPUT_THREAD-$MIGRATION_POLICY-$WHEN_TO_MOVE_OUT-$MAX_MIGRATED_ROWS_SIZE-$ENABLE_SCC-$SCC_MECHANISM-$PRE_MIGRATE-$LOGGING_TYPE-$WAL_GROUP_COMMIT_TIME-$MODEL_CXL_SEARCH_OVERHEAD.txt

        mkdir -p $RESULT_DIR

        $SCRIPT_DIR/run.sh TPCC $PROTOCOL $HOST_NUM $WORKER_NUM mixed 0 0 $USE_CXL_TRANS $USE_OUTPUT_THREAD 1 $MIGRATION_POLICY $WHEN_TO_MOVE_OUT $MAX_MIGRATED_ROWS_SIZE $ENABLE_SCC $SCC_MECHANISM None $TIME_TO_RUN $TIME_TO_WARMUP $LOGGING_TYPE $WAL_GROUP_COMMIT_TIME $MODEL_CXL_SEARCH_OVERHEAD 0 >> $RESULT_FILE 2>&1
        $SCRIPT_DIR/run.sh TPCC $PROTOCOL $HOST_NUM $WORKER_NUM mixed 10 15 $USE_CXL_TRANS $USE_OUTPUT_THREAD 1 $MIGRATION_POLICY $WHEN_TO_MOVE_OUT $MAX_MIGRATED_ROWS_SIZE $ENABLE_SCC $SCC_MECHANISM $PRE_MIGRATE $TIME_TO_RUN $TIME_TO_WARMUP $LOGGING_TYPE $WAL_GROUP_COMMIT_TIME $MODEL_CXL_SEARCH_OVERHEAD 0 >> $RESULT_FILE 2>&1
        $SCRIPT_DIR/run.sh TPCC $PROTOCOL $HOST_NUM $WORKER_NUM mixed 20 30 $USE_CXL_TRANS $USE_OUTPUT_THREAD 1 $MIGRATION_POLICY $WHEN_TO_MOVE_OUT $MAX_MIGRATED_ROWS_SIZE $ENABLE_SCC $SCC_MECHANISM $PRE_MIGRATE $TIME_TO_RUN $TIME_TO_WARMUP $LOGGING_TYPE $WAL_GROUP_COMMIT_TIME $MODEL_CXL_SEARCH_OVERHEAD 0 >> $RESULT_FILE 2>&1
        $SCRIPT_DIR/run.sh TPCC $PROTOCOL $HOST_NUM $WORKER_NUM mixed 30 45 $USE_CXL_TRANS $USE_OUTPUT_THREAD 1 $MIGRATION_POLICY $WHEN_TO_MOVE_OUT $MAX_MIGRATED_ROWS_SIZE $ENABLE_SCC $SCC_MECHANISM $PRE_MIGRATE $TIME_TO_RUN $TIME_TO_WARMUP $LOGGING_TYPE $WAL_GROUP_COMMIT_TIME $MODEL_CXL_SEARCH_OVERHEAD 0 >> $RESULT_FILE 2>&1
        $SCRIPT_DIR/run.sh TPCC $PROTOCOL $HOST_NUM $WORKER_NUM mixed 40 60 $USE_CXL_TRANS $USE_OUTPUT_THREAD 1 $MIGRATION_POLICY $WHEN_TO_MOVE_OUT $MAX_MIGRATED_ROWS_SIZE $ENABLE_SCC $SCC_MECHANISM $PRE_MIGRATE $TIME_TO_RUN $TIME_TO_WARMUP $LOGGING_TYPE $WAL_GROUP_COMMIT_TIME $MODEL_CXL_SEARCH_OVERHEAD 0 >> $RESULT_FILE 2>&1
        $SCRIPT_DIR/run.sh TPCC $PROTOCOL $HOST_NUM $WORKER_NUM mixed 50 75 $USE_CXL_TRANS $USE_OUTPUT_THREAD 1 $MIGRATION_POLICY $WHEN_TO_MOVE_OUT $MAX_MIGRATED_ROWS_SIZE $ENABLE_SCC $SCC_MECHANISM $PRE_MIGRATE $TIME_TO_RUN $TIME_TO_WARMUP $LOGGING_TYPE $WAL_GROUP_COMMIT_TIME $MODEL_CXL_SEARCH_OVERHEAD 0 >> $RESULT_FILE 2>&1
        $SCRIPT_DIR/run.sh TPCC $PROTOCOL $HOST_NUM $WORKER_NUM mixed 60 90 $USE_CXL_TRANS $USE_OUTPUT_THREAD 1 $MIGRATION_POLICY $WHEN_TO_MOVE_OUT $MAX_MIGRATED_ROWS_SIZE $ENABLE_SCC $SCC_MECHANISM $PRE_MIGRATE $TIME_TO_RUN $TIME_TO_WARMUP $LOGGING_TYPE $WAL_GROUP_COMMIT_TIME $MODEL_CXL_SEARCH_OVERHEAD 0 >> $RESULT_FILE 2>&1
}

function run_remote_txn_overhead_ycsb {
        if [ $# != 20 ]; then
                print_usage
                exit -1
        fi

        typeset RESULT_DIR=$1
        typeset PROTOCOL=$2
        typeset HOST_NUM=$3
        typeset WORKER_NUM=$4
        typeset WORKLOAD=$5
        typeset RW_RATIO=$6
        typeset ZIPF_THETA=$7
        typeset USE_CXL_TRANS=$8
        typeset USE_OUTPUT_THREAD=$9
        typeset MIGRATION_POLICY=${10}
        typeset WHEN_TO_MOVE_OUT=${11}
        typeset MAX_MIGRATED_ROWS_SIZE=${12}
        typeset ENABLE_SCC=${13}
        typeset SCC_MECHANISM=${14}
        typeset PRE_MIGRATE=${15}
        typeset LOGGING_TYPE=${16}
        typeset WAL_GROUP_COMMIT_TIME=${17}
        typeset MODEL_CXL_SEARCH_OVERHEAD=${18}
        typeset TIME_TO_RUN=${19}
        typeset TIME_TO_WARMUP=${20}

        typeset KEYS=300000

        typeset RESULT_FILE=$RESULT_DIR/ycsb-$PROTOCOL-$WORKLOAD-$HOST_NUM-$WORKER_NUM-$RW_RATIO-$ZIPF_THETA-$USE_CXL_TRANS-$USE_OUTPUT_THREAD-$MIGRATION_POLICY-$WHEN_TO_MOVE_OUT-$MAX_MIGRATED_ROWS_SIZE-$ENABLE_SCC-$SCC_MECHANISM-$PRE_MIGRATE-$LOGGING_TYPE-$WAL_GROUP_COMMIT_TIME-$MODEL_CXL_SEARCH_OVERHEAD.txt

        mkdir -p $RESULT_DIR

        $SCRIPT_DIR/run.sh YCSB $PROTOCOL $HOST_NUM $WORKER_NUM $WORKLOAD $KEYS $RW_RATIO $ZIPF_THETA 0 $USE_CXL_TRANS $USE_OUTPUT_THREAD 1 $MIGRATION_POLICY $WHEN_TO_MOVE_OUT $MAX_MIGRATED_ROWS_SIZE $ENABLE_SCC $SCC_MECHANISM None $TIME_TO_RUN $TIME_TO_WARMUP $LOGGING_TYPE $WAL_GROUP_COMMIT_TIME $MODEL_CXL_SEARCH_OVERHEAD 0 >> $RESULT_FILE 2>&1
        $SCRIPT_DIR/run.sh YCSB $PROTOCOL $HOST_NUM $WORKER_NUM $WORKLOAD $KEYS $RW_RATIO $ZIPF_THETA 10 $USE_CXL_TRANS $USE_OUTPUT_THREAD 1 $MIGRATION_POLICY $WHEN_TO_MOVE_OUT $MAX_MIGRATED_ROWS_SIZE $ENABLE_SCC $SCC_MECHANISM $PRE_MIGRATE $TIME_TO_RUN $TIME_TO_WARMUP $LOGGING_TYPE $WAL_GROUP_COMMIT_TIME $MODEL_CXL_SEARCH_OVERHEAD 0 >> $RESULT_FILE 2>&1
        $SCRIPT_DIR/run.sh YCSB $PROTOCOL $HOST_NUM $WORKER_NUM $WORKLOAD $KEYS $RW_RATIO $ZIPF_THETA 20 $USE_CXL_TRANS $USE_OUTPUT_THREAD 1 $MIGRATION_POLICY $WHEN_TO_MOVE_OUT $MAX_MIGRATED_ROWS_SIZE $ENABLE_SCC $SCC_MECHANISM $PRE_MIGRATE $TIME_TO_RUN $TIME_TO_WARMUP $LOGGING_TYPE $WAL_GROUP_COMMIT_TIME $MODEL_CXL_SEARCH_OVERHEAD 0 >> $RESULT_FILE 2>&1
        $SCRIPT_DIR/run.sh YCSB $PROTOCOL $HOST_NUM $WORKER_NUM $WORKLOAD $KEYS $RW_RATIO $ZIPF_THETA 30 $USE_CXL_TRANS $USE_OUTPUT_THREAD 1 $MIGRATION_POLICY $WHEN_TO_MOVE_OUT $MAX_MIGRATED_ROWS_SIZE $ENABLE_SCC $SCC_MECHANISM $PRE_MIGRATE $TIME_TO_RUN $TIME_TO_WARMUP $LOGGING_TYPE $WAL_GROUP_COMMIT_TIME $MODEL_CXL_SEARCH_OVERHEAD 0 >> $RESULT_FILE 2>&1
        $SCRIPT_DIR/run.sh YCSB $PROTOCOL $HOST_NUM $WORKER_NUM $WORKLOAD $KEYS $RW_RATIO $ZIPF_THETA 40 $USE_CXL_TRANS $USE_OUTPUT_THREAD 1 $MIGRATION_POLICY $WHEN_TO_MOVE_OUT $MAX_MIGRATED_ROWS_SIZE $ENABLE_SCC $SCC_MECHANISM $PRE_MIGRATE $TIME_TO_RUN $TIME_TO_WARMUP $LOGGING_TYPE $WAL_GROUP_COMMIT_TIME $MODEL_CXL_SEARCH_OVERHEAD 0 >> $RESULT_FILE 2>&1
        $SCRIPT_DIR/run.sh YCSB $PROTOCOL $HOST_NUM $WORKER_NUM $WORKLOAD $KEYS $RW_RATIO $ZIPF_THETA 50 $USE_CXL_TRANS $USE_OUTPUT_THREAD 1 $MIGRATION_POLICY $WHEN_TO_MOVE_OUT $MAX_MIGRATED_ROWS_SIZE $ENABLE_SCC $SCC_MECHANISM $PRE_MIGRATE $TIME_TO_RUN $TIME_TO_WARMUP $LOGGING_TYPE $WAL_GROUP_COMMIT_TIME $MODEL_CXL_SEARCH_OVERHEAD 0 >> $RESULT_FILE 2>&1
        $SCRIPT_DIR/run.sh YCSB $PROTOCOL $HOST_NUM $WORKER_NUM $WORKLOAD $KEYS $RW_RATIO $ZIPF_THETA 60 $USE_CXL_TRANS $USE_OUTPUT_THREAD 1 $MIGRATION_POLICY $WHEN_TO_MOVE_OUT $MAX_MIGRATED_ROWS_SIZE $ENABLE_SCC $SCC_MECHANISM $PRE_MIGRATE $TIME_TO_RUN $TIME_TO_WARMUP $LOGGING_TYPE $WAL_GROUP_COMMIT_TIME $MODEL_CXL_SEARCH_OVERHEAD 0 >> $RESULT_FILE 2>&1
        $SCRIPT_DIR/run.sh YCSB $PROTOCOL $HOST_NUM $WORKER_NUM $WORKLOAD $KEYS $RW_RATIO $ZIPF_THETA 70 $USE_CXL_TRANS $USE_OUTPUT_THREAD 1 $MIGRATION_POLICY $WHEN_TO_MOVE_OUT $MAX_MIGRATED_ROWS_SIZE $ENABLE_SCC $SCC_MECHANISM $PRE_MIGRATE $TIME_TO_RUN $TIME_TO_WARMUP $LOGGING_TYPE $WAL_GROUP_COMMIT_TIME $MODEL_CXL_SEARCH_OVERHEAD 0 >> $RESULT_FILE 2>&1
        $SCRIPT_DIR/run.sh YCSB $PROTOCOL $HOST_NUM $WORKER_NUM $WORKLOAD $KEYS $RW_RATIO $ZIPF_THETA 80 $USE_CXL_TRANS $USE_OUTPUT_THREAD 1 $MIGRATION_POLICY $WHEN_TO_MOVE_OUT $MAX_MIGRATED_ROWS_SIZE $ENABLE_SCC $SCC_MECHANISM $PRE_MIGRATE $TIME_TO_RUN $TIME_TO_WARMUP $LOGGING_TYPE $WAL_GROUP_COMMIT_TIME $MODEL_CXL_SEARCH_OVERHEAD 0 >> $RESULT_FILE 2>&1
        $SCRIPT_DIR/run.sh YCSB $PROTOCOL $HOST_NUM $WORKER_NUM $WORKLOAD $KEYS $RW_RATIO $ZIPF_THETA 90 $USE_CXL_TRANS $USE_OUTPUT_THREAD 1 $MIGRATION_POLICY $WHEN_TO_MOVE_OUT $MAX_MIGRATED_ROWS_SIZE $ENABLE_SCC $SCC_MECHANISM $PRE_MIGRATE $TIME_TO_RUN $TIME_TO_WARMUP $LOGGING_TYPE $WAL_GROUP_COMMIT_TIME $MODEL_CXL_SEARCH_OVERHEAD 0 >> $RESULT_FILE 2>&1
        $SCRIPT_DIR/run.sh YCSB $PROTOCOL $HOST_NUM $WORKER_NUM $WORKLOAD $KEYS $RW_RATIO $ZIPF_THETA 100 $USE_CXL_TRANS $USE_OUTPUT_THREAD 1 $MIGRATION_POLICY $WHEN_TO_MOVE_OUT $MAX_MIGRATED_ROWS_SIZE $ENABLE_SCC $SCC_MECHANISM $PRE_MIGRATE $TIME_TO_RUN $TIME_TO_WARMUP $LOGGING_TYPE $WAL_GROUP_COMMIT_TIME $MODEL_CXL_SEARCH_OVERHEAD 0 >> $RESULT_FILE 2>&1
}

function run_tpcc_single {
        if [ $# != 19 ]; then
                print_usage
                exit -1
        fi

        typeset RESULT_DIR=$1
        typeset PROTOCOL=$2
        typeset HOST_NUM=$3
        typeset WORKER_NUM=$4
        typeset REMOTE_PAYMENT_PERC=$5
        typeset REMOTE_NEWORDER_PERC=$6
        typeset USE_CXL_TRANS=$7
        typeset USE_OUTPUT_THREAD=$8
        typeset MIGRATION_POLICY=$9
        typeset WHEN_TO_MOVE_OUT=${10}
        typeset MAX_MIGRATED_ROWS_SIZE=${11}
        typeset ENABLE_SCC=${12}
        typeset SCC_MECHANISM=${13}
        typeset PRE_MIGRATE=${14}
        typeset LOGGING_TYPE=${15}
        typeset WAL_GROUP_COMMIT_TIME=${16}
        typeset MODEL_CXL_SEARCH_OVERHEAD=${17}
        typeset TIME_TO_RUN=${18}
        typeset TIME_TO_WARMUP=${19}

        typeset RESULT_FILE=$RESULT_DIR/tpcc-$PROTOCOL-$HOST_NUM-$WORKER_NUM-$USE_CXL_TRANS-$USE_OUTPUT_THREAD-$MIGRATION_POLICY-$WHEN_TO_MOVE_OUT-$MAX_MIGRATED_ROWS_SIZE-$ENABLE_SCC-$SCC_MECHANISM-$PRE_MIGRATE-$LOGGING_TYPE-$WAL_GROUP_COMMIT_TIME-$MODEL_CXL_SEARCH_OVERHEAD.txt

        mkdir -p $RESULT_DIR

        $SCRIPT_DIR/run.sh TPCC $PROTOCOL $HOST_NUM $WORKER_NUM mixed $REMOTE_PAYMENT_PERC $REMOTE_NEWORDER_PERC $USE_CXL_TRANS $USE_OUTPUT_THREAD 1 $MIGRATION_POLICY $WHEN_TO_MOVE_OUT $MAX_MIGRATED_ROWS_SIZE $ENABLE_SCC $SCC_MECHANISM $PRE_MIGRATE $TIME_TO_RUN $TIME_TO_WARMUP $LOGGING_TYPE $WAL_GROUP_COMMIT_TIME $MODEL_CXL_SEARCH_OVERHEAD 0 >> $RESULT_FILE 2>&1
}

function run_ycsb_single {
        if [ $# != 21 ]; then
                print_usage
                exit -1
        fi

        typeset RESULT_DIR=$1
        typeset PROTOCOL=$2
        typeset HOST_NUM=$3
        typeset WORKER_NUM=$4
        typeset WORKLOAD=$5
        typeset RW_RATIO=$6
        typeset ZIPF_THETA=$7
        typeset REMOTE_RATIO=$8
        typeset USE_CXL_TRANS=$9
        typeset USE_OUTPUT_THREAD=${10}
        typeset MIGRATION_POLICY=${11}
        typeset WHEN_TO_MOVE_OUT=${12}
        typeset MAX_MIGRATED_ROWS_SIZE=${13}
        typeset ENABLE_SCC=${14}
        typeset SCC_MECHANISM=${15}
        typeset PRE_MIGRATE=${16}
        typeset LOGGING_TYPE=${17}
        typeset WAL_GROUP_COMMIT_TIME=${18}
        typeset MODEL_CXL_SEARCH_OVERHEAD=${19}
        typeset TIME_TO_RUN=${20}
        typeset TIME_TO_WARMUP=${21}

        typeset KEYS=300000

        typeset RESULT_FILE=$RESULT_DIR/ycsb-$PROTOCOL-$WORKLOAD-$HOST_NUM-$WORKER_NUM-$RW_RATIO-$ZIPF_THETA-$USE_CXL_TRANS-$USE_OUTPUT_THREAD-$MIGRATION_POLICY-$WHEN_TO_MOVE_OUT-$MAX_MIGRATED_ROWS_SIZE-$ENABLE_SCC-$SCC_MECHANISM-$PRE_MIGRATE-$LOGGING_TYPE-$WAL_GROUP_COMMIT_TIME-$MODEL_CXL_SEARCH_OVERHEAD.txt

        mkdir -p $RESULT_DIR

        $SCRIPT_DIR/run.sh YCSB $PROTOCOL $HOST_NUM $WORKER_NUM $WORKLOAD $KEYS $RW_RATIO $ZIPF_THETA $REMOTE_RATIO $USE_CXL_TRANS $USE_OUTPUT_THREAD 1 $MIGRATION_POLICY $WHEN_TO_MOVE_OUT $MAX_MIGRATED_ROWS_SIZE $ENABLE_SCC $SCC_MECHANISM $PRE_MIGRATE $TIME_TO_RUN $TIME_TO_WARMUP $LOGGING_TYPE $WAL_GROUP_COMMIT_TIME $MODEL_CXL_SEARCH_OVERHEAD 0 >> $RESULT_FILE 2>&1
}
