#! /bin/bash

set -uo pipefail
# set -x

typeset SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
typeset current_date_time="`date +%Y%m%d%H%M`"

source $SCRIPT_DIR/common.sh

function print_usage {
        echo "[usage] $0 RESULT_ROOT_DIR"
}

if [ $# != 1 ]; then
        print_usage
        exit -1
fi

typeset RESULT_ROOT_DIR=$1

########### General Configuration BEGIN ###########

# common parameters
typeset HOST_NUM=8
typeset WORKER_NUM=3
typeset OLD_WORKER_NUM=2

typeset DEFAULT_WAL_GROUP_COMMIT_TIME=10000 # 10 ms

typeset DEFAULT_HCC_SIZE_LIMIT=$(( 1024*1024*200 ))     # 200 MB

typeset DATA_MOVEMENT_EXP_HCC_SIZE_LIMIT_1=$(( 1024*1024*200 ))         # 200 MB
typeset DATA_MOVEMENT_EXP_HCC_SIZE_LIMIT_2=$(( 1024*1024*150 ))         # 150 MB
typeset DATA_MOVEMENT_EXP_HCC_SIZE_LIMIT_3=$(( 1024*1024*100 ))         # 100 MB
typeset DATA_MOVEMENT_EXP_HCC_SIZE_LIMIT_4=$(( 1024*1024*50 ))          # 50 MB
typeset DATA_MOVEMENT_EXP_HCC_SIZE_LIMIT_5=$(( 1024*1024*10 ))          # 10 MB

# common parameters for TPCC
typeset TPCC_RUN_TIME=60
typeset TPCC_WARMUP_TIME=30

# common parameters for YCSB
typeset YCSB_RUN_TIME=60
typeset YCSB_WARMUP_TIME=30

typeset READ_INTENSIVE_RW_RATIO=95
typeset WRITE_INTENSIVE_RW_RATIO=50

########### General Configuration END ###########


########### Shortcut BEGIN ###########

typeset RESULT_DIR=$RESULT_ROOT_DIR/shortcut
mkdir -p $RESULT_DIR

# TPCC
run_remote_txn_overhead_tpcc $RESULT_DIR TwoPLPasha $HOST_NUM $WORKER_NUM 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough NonPart GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 1 $TPCC_RUN_TIME $TPCC_WARMUP_TIME

# YCSB read-intensive + 0.7 skewness
run_remote_txn_overhead_ycsb $RESULT_DIR TwoPLPasha $HOST_NUM $WORKER_NUM rmw $READ_INTENSIVE_RW_RATIO 0.7 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough NonPart GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 1 $YCSB_RUN_TIME $YCSB_WARMUP_TIME

########### Shortcut END ###########


########### CLOCK BEGIN ###########

typeset RESULT_DIR=$RESULT_ROOT_DIR/migration_policy
mkdir -p $RESULT_DIR

run_ycsb_single $RESULT_DIR TwoPLPasha $HOST_NUM $WORKER_NUM rmw $READ_INTENSIVE_RW_RATIO 0.7 100 1 0 LRU OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME
run_ycsb_single $RESULT_DIR TwoPLPasha $HOST_NUM $WORKER_NUM rmw $READ_INTENSIVE_RW_RATIO 0.7 100 1 0 LRU OnDemand $DATA_MOVEMENT_EXP_HCC_SIZE_LIMIT_3 1 WriteThrough None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME

########### CLOCK END ###########


########### Tracking Tuple Modification BEGIN ###########

# typeset RESULT_DIR=$RESULT_ROOT_DIR/dirty
# mkdir -p $RESULT_DIR

# run_remote_txn_overhead_ycsb $RESULT_DIR TwoPLPasha $HOST_NUM $WORKER_NUM rmw 100 0.7 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough NonPart GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME     # Tigon

# Manual: disable the optimization and run this again

########### Tracking Tuple Modification BEGIN ###########


########### YCSB 0.99 BEGIN ###########

typeset RESULT_DIR=$RESULT_ROOT_DIR/ycsb-0.99
mkdir -p $RESULT_DIR

run_ycsb_single $RESULT_DIR TwoPL $HOST_NUM $WORKER_NUM rmw 100 0.99 100 1 0 NoMoveOut OnDemand 0 0 NoOP None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME           # TwoPL-CXL-improved
run_ycsb_single $RESULT_DIR Sundial $HOST_NUM $WORKER_NUM rmw 100 0.99 100 1 0 NoMoveOut OnDemand 0 0 NoOP None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME         # Sundial-CXL-improved
run_ycsb_single $RESULT_DIR TwoPLPasha $HOST_NUM $WORKER_NUM rmw 100 0.99 100 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough NonPart GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME     # Tigon

run_ycsb_single $RESULT_DIR TwoPL $HOST_NUM $WORKER_NUM rmw 0 0.99 100 1 0 NoMoveOut OnDemand 0 0 NoOP None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME           # TwoPL-CXL-improved
run_ycsb_single $RESULT_DIR Sundial $HOST_NUM $WORKER_NUM rmw 0 0.99 100 1 0 NoMoveOut OnDemand 0 0 NoOP None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME         # Sundial-CXL-improved
run_ycsb_single $RESULT_DIR TwoPLPasha $HOST_NUM $WORKER_NUM rmw 0 0.99 100 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough NonPart GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME     # Tigon

run_ycsb_single $RESULT_DIR TwoPL $HOST_NUM $WORKER_NUM rmw $READ_INTENSIVE_RW_RATIO 0.99 100 1 0 NoMoveOut OnDemand 0 0 NoOP None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME           # TwoPL-CXL-improved
run_ycsb_single $RESULT_DIR Sundial $HOST_NUM $WORKER_NUM rmw $READ_INTENSIVE_RW_RATIO 0.99 100 1 0 NoMoveOut OnDemand 0 0 NoOP None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME         # Sundial-CXL-improved
run_ycsb_single $RESULT_DIR TwoPLPasha $HOST_NUM $WORKER_NUM rmw $READ_INTENSIVE_RW_RATIO 0.99 100 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough NonPart GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME     # Tigon

run_ycsb_single $RESULT_DIR TwoPL $HOST_NUM $WORKER_NUM rmw $WRITE_INTENSIVE_RW_RATIO 0.99 100 1 0 NoMoveOut OnDemand 0 0 NoOP None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME           # TwoPL-CXL-improved
run_ycsb_single $RESULT_DIR Sundial $HOST_NUM $WORKER_NUM rmw $WRITE_INTENSIVE_RW_RATIO 0.99 100 1 0 NoMoveOut OnDemand 0 0 NoOP None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME         # Sundial-CXL-improved
run_ycsb_single $RESULT_DIR TwoPLPasha $HOST_NUM $WORKER_NUM rmw $WRITE_INTENSIVE_RW_RATIO 0.99 100 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough NonPart GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME     # Tigon

########### YCSB 0.99 END ###########


########### Logging BEGIN ###########

typeset RESULT_DIR=$RESULT_ROOT_DIR/logging
mkdir -p $RESULT_DIR

# TPCC
run_tpcc_single $RESULT_DIR TwoPLPasha $HOST_NUM $WORKER_NUM 0 0 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough None BLACKHOLE 0 0 $TPCC_RUN_TIME $TPCC_WARMUP_TIME
run_tpcc_single $RESULT_DIR TwoPLPasha $HOST_NUM $WORKER_NUM 0 0 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough None GROUP_WAL 50000 0 $TPCC_RUN_TIME $TPCC_WARMUP_TIME
run_tpcc_single $RESULT_DIR TwoPLPasha $HOST_NUM $WORKER_NUM 0 0 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough None GROUP_WAL 40000 0 $TPCC_RUN_TIME $TPCC_WARMUP_TIME
run_tpcc_single $RESULT_DIR TwoPLPasha $HOST_NUM $WORKER_NUM 0 0 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough None GROUP_WAL 30000 0 $TPCC_RUN_TIME $TPCC_WARMUP_TIME
run_tpcc_single $RESULT_DIR TwoPLPasha $HOST_NUM $WORKER_NUM 0 0 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough None GROUP_WAL 20000 0 $TPCC_RUN_TIME $TPCC_WARMUP_TIME
run_tpcc_single $RESULT_DIR TwoPLPasha $HOST_NUM $WORKER_NUM 0 0 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough None GROUP_WAL 10000 0 $TPCC_RUN_TIME $TPCC_WARMUP_TIME
run_tpcc_single $RESULT_DIR TwoPLPasha $HOST_NUM $WORKER_NUM 0 0 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough None GROUP_WAL 5000 0 $TPCC_RUN_TIME $TPCC_WARMUP_TIME
run_tpcc_single $RESULT_DIR TwoPLPasha $HOST_NUM $WORKER_NUM 0 0 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough None GROUP_WAL 1000 0 $TPCC_RUN_TIME $TPCC_WARMUP_TIME

# YCSB: write-intensive + 0.7 skewness
run_ycsb_single $RESULT_DIR TwoPLPasha $HOST_NUM $WORKER_NUM rmw 50 0.7 0 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough None BLACKHOLE 0 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME
run_ycsb_single $RESULT_DIR TwoPLPasha $HOST_NUM $WORKER_NUM rmw 50 0.7 0 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough None GROUP_WAL 50000 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME
run_ycsb_single $RESULT_DIR TwoPLPasha $HOST_NUM $WORKER_NUM rmw 50 0.7 0 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough None GROUP_WAL 40000 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME
run_ycsb_single $RESULT_DIR TwoPLPasha $HOST_NUM $WORKER_NUM rmw 50 0.7 0 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough None GROUP_WAL 30000 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME
run_ycsb_single $RESULT_DIR TwoPLPasha $HOST_NUM $WORKER_NUM rmw 50 0.7 0 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough None GROUP_WAL 20000 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME
run_ycsb_single $RESULT_DIR TwoPLPasha $HOST_NUM $WORKER_NUM rmw 50 0.7 0 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough None GROUP_WAL 10000 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME
run_ycsb_single $RESULT_DIR TwoPLPasha $HOST_NUM $WORKER_NUM rmw 50 0.7 0 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough None GROUP_WAL 5000 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME
run_ycsb_single $RESULT_DIR TwoPLPasha $HOST_NUM $WORKER_NUM rmw 50 0.7 0 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough None GROUP_WAL 1000 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME

########### Logging END ###########


########### Scalability BEGIN ###########

typeset RESULT_DIR=$RESULT_ROOT_DIR/scalability
mkdir -p $RESULT_DIR

# TPCC
# TwoPL
run_tpcc_single $RESULT_DIR TwoPL 1 $WORKER_NUM 60 90 1 0 NoMoveOut OnDemand 0 0 NoOP None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $TPCC_RUN_TIME $TPCC_WARMUP_TIME
run_tpcc_single $RESULT_DIR TwoPL 2 $WORKER_NUM 60 90 1 0 NoMoveOut OnDemand 0 0 NoOP None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $TPCC_RUN_TIME $TPCC_WARMUP_TIME
run_tpcc_single $RESULT_DIR TwoPL 4 $WORKER_NUM 60 90 1 0 NoMoveOut OnDemand 0 0 NoOP None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $TPCC_RUN_TIME $TPCC_WARMUP_TIME
run_tpcc_single $RESULT_DIR TwoPL 6 $WORKER_NUM 60 90 1 0 NoMoveOut OnDemand 0 0 NoOP None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $TPCC_RUN_TIME $TPCC_WARMUP_TIME
run_tpcc_single $RESULT_DIR TwoPL 8 $WORKER_NUM 60 90 1 0 NoMoveOut OnDemand 0 0 NoOP None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $TPCC_RUN_TIME $TPCC_WARMUP_TIME

# Sundial
run_tpcc_single $RESULT_DIR Sundial 1 $WORKER_NUM 60 90 1 0 NoMoveOut OnDemand 0 0 NoOP None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $TPCC_RUN_TIME $TPCC_WARMUP_TIME
run_tpcc_single $RESULT_DIR Sundial 2 $WORKER_NUM 60 90 1 0 NoMoveOut OnDemand 0 0 NoOP None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $TPCC_RUN_TIME $TPCC_WARMUP_TIME
run_tpcc_single $RESULT_DIR Sundial 4 $WORKER_NUM 60 90 1 0 NoMoveOut OnDemand 0 0 NoOP None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $TPCC_RUN_TIME $TPCC_WARMUP_TIME
run_tpcc_single $RESULT_DIR Sundial 6 $WORKER_NUM 60 90 1 0 NoMoveOut OnDemand 0 0 NoOP None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $TPCC_RUN_TIME $TPCC_WARMUP_TIME
run_tpcc_single $RESULT_DIR Sundial 8 $WORKER_NUM 60 90 1 0 NoMoveOut OnDemand 0 0 NoOP None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $TPCC_RUN_TIME $TPCC_WARMUP_TIME

# Tigon
run_tpcc_single $RESULT_DIR TwoPLPasha 1 $WORKER_NUM 60 90 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $TPCC_RUN_TIME $TPCC_WARMUP_TIME
run_tpcc_single $RESULT_DIR TwoPLPasha 2 $WORKER_NUM 60 90 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough NonPart GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $TPCC_RUN_TIME $TPCC_WARMUP_TIME
run_tpcc_single $RESULT_DIR TwoPLPasha 4 $WORKER_NUM 60 90 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough NonPart GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $TPCC_RUN_TIME $TPCC_WARMUP_TIME
run_tpcc_single $RESULT_DIR TwoPLPasha 6 $WORKER_NUM 60 90 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough NonPart GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $TPCC_RUN_TIME $TPCC_WARMUP_TIME
run_tpcc_single $RESULT_DIR TwoPLPasha 8 $WORKER_NUM 60 90 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough NonPart GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $TPCC_RUN_TIME $TPCC_WARMUP_TIME

# YCSB: read-heavy + 0.7 skewness
# TwoPL
run_ycsb_single $RESULT_DIR TwoPL 1 $WORKER_NUM rmw 95 0.7 100 1 0 NoMoveOut OnDemand 0 0 NoOP None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME
run_ycsb_single $RESULT_DIR TwoPL 2 $WORKER_NUM rmw 95 0.7 100 1 0 NoMoveOut OnDemand 0 0 NoOP None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME
run_ycsb_single $RESULT_DIR TwoPL 4 $WORKER_NUM rmw 95 0.7 100 1 0 NoMoveOut OnDemand 0 0 NoOP None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME
run_ycsb_single $RESULT_DIR TwoPL 6 $WORKER_NUM rmw 95 0.7 100 1 0 NoMoveOut OnDemand 0 0 NoOP None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME
run_ycsb_single $RESULT_DIR TwoPL 8 $WORKER_NUM rmw 95 0.7 100 1 0 NoMoveOut OnDemand 0 0 NoOP None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME

# Sundial
run_ycsb_single $RESULT_DIR Sundial 1 $WORKER_NUM rmw 95 0.7 100 1 0 NoMoveOut OnDemand 0 0 NoOP None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME
run_ycsb_single $RESULT_DIR Sundial 2 $WORKER_NUM rmw 95 0.7 100 1 0 NoMoveOut OnDemand 0 0 NoOP None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME
run_ycsb_single $RESULT_DIR Sundial 4 $WORKER_NUM rmw 95 0.7 100 1 0 NoMoveOut OnDemand 0 0 NoOP None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME
run_ycsb_single $RESULT_DIR Sundial 6 $WORKER_NUM rmw 95 0.7 100 1 0 NoMoveOut OnDemand 0 0 NoOP None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME
run_ycsb_single $RESULT_DIR Sundial 8 $WORKER_NUM rmw 95 0.7 100 1 0 NoMoveOut OnDemand 0 0 NoOP None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME

# Tigon
run_ycsb_single $RESULT_DIR TwoPLPasha 1 $WORKER_NUM rmw 95 0.7 100 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough None GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME
run_ycsb_single $RESULT_DIR TwoPLPasha 2 $WORKER_NUM rmw 95 0.7 100 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough NonPart GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME
run_ycsb_single $RESULT_DIR TwoPLPasha 4 $WORKER_NUM rmw 95 0.7 100 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough NonPart GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME
run_ycsb_single $RESULT_DIR TwoPLPasha 6 $WORKER_NUM rmw 95 0.7 100 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough NonPart GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME
run_ycsb_single $RESULT_DIR TwoPLPasha 8 $WORKER_NUM rmw 95 0.7 100 1 0 Clock OnDemand $DEFAULT_HCC_SIZE_LIMIT 1 WriteThrough NonPart GROUP_WAL $DEFAULT_WAL_GROUP_COMMIT_TIME 0 $YCSB_RUN_TIME $YCSB_WARMUP_TIME

########### Scalability END ###########
